DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(50),
    NAME VARCHAR(50),
    ADDR VARCHAR(100)
);

-- INSERT 구문
COMMIT;
SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE ID = 'ASDASD' AND PASSWORD = 'ASDASD' ;
INSERT INTO MEMBER VALUES ('ASDASD','ASDASD','SAD','DAS');
UPDATE MEMBER SET NAME = 'JUNWOO', PASSWORD = '1234', ADDR = 'ASD' WHERE ID = 'ASDASD';

DROP TABLE MEMBER2;
CREATE TABLE MEMBER2(
    MEMBERID VARCHAR(50) PRIMARY KEY,
    MEMBERPASS VARCHAR(50),
    MEMBERNAME VARCHAR(50),
    MEMBERADDR VARCHAR(100)
);

INSERT INTO MEMBER2(MEMBERID, MEMBERPASS, MEMBERNAME, MEMBERADDR)
SELECT ID, PASSWORD, NAME, ADDR FROM MEMBER;

COMMIT;

SELECT * FROM MEMBER2;