DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR(50),
    PASSWORD VARCHAR(50),
    NAME VARCHAR(50),
    ADDR VARCHAR(100)
);

-- INSERT 구문
COMMIT;
SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE (ID = ASDASD AND PASSWORD = ASDASD) ;
INSERT INTO MEMBER VALUES ('ASDASD','ASDASD','SAD','DAS');
